#!/bin/bash

HOOKS_DIR="$(cd "$(dirname "$0")" && pwd -P)"

RED="\033[0;31m"
LIGHT_RED="\033[1;31m"
GREEN="\033[0;32m"
LIGHT_GREEN="\033[1;32m"
GRAY="\033[0;37m"
LIGHT_GRAY="\033[1;37m"
MAGENTA="\033[0;35m"
LIGHT_MAGENTA="\033[1;35m"
RESET="\033[0m"


function check_hook_status_code {
    if [ $1 -ne 0 ]; then
        echo -e "${RED}"
        echo
        echo "ERRORS SPOTED"
        echo "Please fix errors before commiting"
        echo
        echo -e "${RESET}"

        exit $RESULT
    fi
}

function run_hooks {
    for hook_file in "${HOOKS_DIR}/pre-commit-hooks/"*.sh; do
        if [[ -x "${hook_file}" ]]; then
            "${hook_file}"
            RESULT=$?
            check_hook_status_code $RESULT
         else
            echo "SKIPPING NOT EXECUTABLE FILE: \"${hook_file}\""
        fi
    done
}


echo -e "${GREEN}"
echo -e '\n\t--- pre-commit hooks BEGIN ---\n'
echo -e "${RESET}"

run_hooks;

echo -e "${GREEN}"
echo -e '\n\t--- pre-commit hooks END ---\n'
echo -e "${RESET}"

exit 0;
